services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: home_server_backend
    network_mode: "host"
    environment:
      SERVER_PORT: 8000
      SQLITE_PATH: /app/data/home_server_hub.db
      IMAGES_DIR: /app/data/images
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
